[package]
name = "linearpl"
version = "0.1.0"
edition = "2021"
description = """
	particle system library for use with macroquad
"""
readme = "README.md"

[dependencies]
macroquad = "0.4.13"
rand = "0.9.0"
